#############################################################################
# Makefile for building: PIP
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  PIP.pro
# Template: app
# Command: /home/liuziang/Desktop/QT/5.12.12/gcc_64/bin/qmake -o Makefile PIP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DTRILIBRARY -DANSI_DECLARATORS -DNO_TIMER -DLINUX -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I-I -Itriangulation -I-I -Idb -I-I -Ijoin -I-I -Iexperiment -I-I -isystem /usr/local/include -I-I -isystem /usr/include/boost -I-I -I/usr/local/cuda/include/ -I../QT/5.12.12/gcc_64/include -I../QT/5.12.12/gcc_64/include/QtOpenGL -I../QT/5.12.12/gcc_64/include/QtWidgets -I../QT/5.12.12/gcc_64/include/QtGui -I../QT/5.12.12/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../QT/5.12.12/gcc_64/mkspecs/linux-g++
QMAKE         = /home/liuziang/Desktop/QT/5.12.12/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/liuziang/Desktop/QT/5.12.12/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/liuziang/Desktop/QT/5.12.12/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PIP1.0.0
DISTDIR = /home/liuziang/Desktop/PIP/.tmp/PIP1.0.0
LINK          = g++
LFLAGS        = -fopenmp -Wl,-rpath,/home/liuziang/Desktop/QT/5.12.12/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib/ -lGLEW -lboost_iostreams -lboost_program_options /home/liuziang/Desktop/QT/5.12.12/gcc_64/lib/libQt5OpenGL.so /home/liuziang/Desktop/QT/5.12.12/gcc_64/lib/libQt5Widgets.so /home/liuziang/Desktop/QT/5.12.12/gcc_64/lib/libQt5Gui.so /home/liuziang/Desktop/QT/5.12.12/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		db/DataHandler.cpp \
		triangulation/clip2tri/clip2tri.cpp \
		triangulation/clipper/clipper.cpp \
		triangulation/poly2tri/common/shapes.cc \
		triangulation/poly2tri/sweep/advancing_front.cc \
		triangulation/poly2tri/sweep/cdt.cc \
		triangulation/poly2tri/sweep/sweep.cc \
		triangulation/poly2tri/sweep/sweep_context.cc \
		join/GLData.cpp \
		join/GLFunction.cpp \
		join/GLHandler.cpp \
		join/RasterJoin.cpp qrc_shaders.cpp
OBJECTS       = main.o \
		DataHandler.o \
		clip2tri.o \
		clipper.o \
		shapes.o \
		advancing_front.o \
		cdt.o \
		sweep.o \
		sweep_context.o \
		GLData.o \
		GLFunction.o \
		GLHandler.o \
		RasterJoin.o \
		qrc_shaders.o
DIST          = ../QT/5.12.12/gcc_64/mkspecs/features/spec_pre.prf \
		../QT/5.12.12/gcc_64/mkspecs/common/unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/linux.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/sanitize.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/gcc-base.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/g++-base.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/g++-unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/qconfig.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/features/qt_functions.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qt_config.prf \
		../QT/5.12.12/gcc_64/mkspecs/linux-g++/qmake.conf \
		../QT/5.12.12/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../QT/5.12.12/gcc_64/mkspecs/features/exclusive_builds.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/toolchain.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/default_pre.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/resolve_config.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/default_post.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qml_debug.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/warn_on.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qt.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/resources.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/moc.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/unix/opengl.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/uic.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/unix/thread.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qmake_use.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/file_copies.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/testcase_targets.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/exceptions.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/yacc.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/lex.prf \
		PIP.pro db/DataHandler.hpp \
		triangulation/clip2tri/clip2tri.h \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/common/utils.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/poly2tri.h \
		triangulation/Triangle.hpp \
		triangulation/TestTriangulation.hpp \
		join/GLData.hpp \
		join/GLFunction.hpp \
		join/GLHandler.hpp \
		join/RasterJoin.hpp \
		experiment/forexperiment.h main.cpp \
		db/DataHandler.cpp \
		triangulation/clip2tri/clip2tri.cpp \
		triangulation/clipper/clipper.cpp \
		triangulation/poly2tri/common/shapes.cc \
		triangulation/poly2tri/sweep/advancing_front.cc \
		triangulation/poly2tri/sweep/cdt.cc \
		triangulation/poly2tri/sweep/sweep.cc \
		triangulation/poly2tri/sweep/sweep_context.cc \
		join/GLData.cpp \
		join/GLFunction.cpp \
		join/GLHandler.cpp \
		join/RasterJoin.cpp
QMAKE_TARGET  = PIP
DESTDIR       = 
TARGET        = PIP


first: all
####### Build rules

PIP:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PIP.pro ../QT/5.12.12/gcc_64/mkspecs/linux-g++/qmake.conf ../QT/5.12.12/gcc_64/mkspecs/features/spec_pre.prf \
		../QT/5.12.12/gcc_64/mkspecs/common/unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/linux.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/sanitize.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/gcc-base.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/g++-base.conf \
		../QT/5.12.12/gcc_64/mkspecs/common/g++-unix.conf \
		../QT/5.12.12/gcc_64/mkspecs/qconfig.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QT/5.12.12/gcc_64/mkspecs/features/qt_functions.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qt_config.prf \
		../QT/5.12.12/gcc_64/mkspecs/linux-g++/qmake.conf \
		../QT/5.12.12/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../QT/5.12.12/gcc_64/mkspecs/features/exclusive_builds.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/toolchain.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/default_pre.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/resolve_config.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/default_post.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qml_debug.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/warn_on.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qt.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/resources.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/moc.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/unix/opengl.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/uic.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/unix/thread.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/qmake_use.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/file_copies.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/testcase_targets.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/exceptions.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/yacc.prf \
		../QT/5.12.12/gcc_64/mkspecs/features/lex.prf \
		PIP.pro \
		shaders.qrc
	$(QMAKE) -o Makefile PIP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../QT/5.12.12/gcc_64/mkspecs/features/spec_pre.prf:
../QT/5.12.12/gcc_64/mkspecs/common/unix.conf:
../QT/5.12.12/gcc_64/mkspecs/common/linux.conf:
../QT/5.12.12/gcc_64/mkspecs/common/sanitize.conf:
../QT/5.12.12/gcc_64/mkspecs/common/gcc-base.conf:
../QT/5.12.12/gcc_64/mkspecs/common/gcc-base-unix.conf:
../QT/5.12.12/gcc_64/mkspecs/common/g++-base.conf:
../QT/5.12.12/gcc_64/mkspecs/common/g++-unix.conf:
../QT/5.12.12/gcc_64/mkspecs/qconfig.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../QT/5.12.12/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../QT/5.12.12/gcc_64/mkspecs/features/qt_functions.prf:
../QT/5.12.12/gcc_64/mkspecs/features/qt_config.prf:
../QT/5.12.12/gcc_64/mkspecs/linux-g++/qmake.conf:
../QT/5.12.12/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../QT/5.12.12/gcc_64/mkspecs/features/exclusive_builds.prf:
../QT/5.12.12/gcc_64/mkspecs/features/toolchain.prf:
../QT/5.12.12/gcc_64/mkspecs/features/default_pre.prf:
../QT/5.12.12/gcc_64/mkspecs/features/resolve_config.prf:
../QT/5.12.12/gcc_64/mkspecs/features/default_post.prf:
../QT/5.12.12/gcc_64/mkspecs/features/qml_debug.prf:
../QT/5.12.12/gcc_64/mkspecs/features/warn_on.prf:
../QT/5.12.12/gcc_64/mkspecs/features/qt.prf:
../QT/5.12.12/gcc_64/mkspecs/features/resources.prf:
../QT/5.12.12/gcc_64/mkspecs/features/moc.prf:
../QT/5.12.12/gcc_64/mkspecs/features/unix/opengl.prf:
../QT/5.12.12/gcc_64/mkspecs/features/uic.prf:
../QT/5.12.12/gcc_64/mkspecs/features/unix/thread.prf:
../QT/5.12.12/gcc_64/mkspecs/features/qmake_use.prf:
../QT/5.12.12/gcc_64/mkspecs/features/file_copies.prf:
../QT/5.12.12/gcc_64/mkspecs/features/testcase_targets.prf:
../QT/5.12.12/gcc_64/mkspecs/features/exceptions.prf:
../QT/5.12.12/gcc_64/mkspecs/features/yacc.prf:
../QT/5.12.12/gcc_64/mkspecs/features/lex.prf:
PIP.pro:
shaders.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile PIP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile PIP

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents shaders.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../QT/5.12.12/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents db/DataHandler.hpp triangulation/clip2tri/clip2tri.h triangulation/clipper/clipper.hpp triangulation/poly2tri/common/shapes.h triangulation/poly2tri/common/utils.h triangulation/poly2tri/sweep/advancing_front.h triangulation/poly2tri/sweep/cdt.h triangulation/poly2tri/sweep/sweep.h triangulation/poly2tri/sweep/sweep_context.h triangulation/poly2tri/poly2tri.h triangulation/Triangle.hpp triangulation/TestTriangulation.hpp join/GLData.hpp join/GLFunction.hpp join/GLHandler.hpp join/RasterJoin.hpp experiment/forexperiment.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp db/DataHandler.cpp triangulation/clip2tri/clip2tri.cpp triangulation/clipper/clipper.cpp triangulation/poly2tri/common/shapes.cc triangulation/poly2tri/sweep/advancing_front.cc triangulation/poly2tri/sweep/cdt.cc triangulation/poly2tri/sweep/sweep.cc triangulation/poly2tri/sweep/sweep_context.cc join/GLData.cpp join/GLFunction.cpp join/GLHandler.cpp join/RasterJoin.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_shaders.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp
qrc_shaders.cpp: shaders.qrc \
		../QT/5.12.12/gcc_64/bin/rcc \
		shaders/polygon.frag \
		shaders/points.vert \
		shaders/polygon.vert \
		shaders/points.frag
	/home/liuziang/Desktop/QT/5.12.12/gcc_64/bin/rcc -name shaders shaders.qrc -o qrc_shaders.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../QT/5.12.12/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -fopenmp -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../QT/5.12.12/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp db/DataHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QVector \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtGui/QPolygonF \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		../QT/5.12.12/gcc_64/include/QtCore/QString \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/clip2tri/clip2tri.h \
		join/GLHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLContext \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglcontext.h \
		../QT/5.12.12/gcc_64/include/QtCore/QObject \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/QScopedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/QSurfaceFormat \
		../QT/5.12.12/gcc_64/include/QtGui/qsurfaceformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qt_windows.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengles2ext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOffscreenSurface \
		../QT/5.12.12/gcc_64/include/QtGui/qoffscreensurface.h \
		../QT/5.12.12/gcc_64/include/QtGui/qsurface.h \
		../QT/5.12.12/gcc_64/include/QtCore/QSharedPointer \
		join/GLFunction.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QPointF \
		../QT/5.12.12/gcc_64/include/QtCore/QSize \
		join/GLData.hpp \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qgl.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qwidget.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs_win.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpalette.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcolor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgb.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgba64.h \
		../QT/5.12.12/gcc_64/include/QtGui/qbrush.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix.h \
		../QT/5.12.12/gcc_64/include/QtGui/qregion.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdatastream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qline.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtransform.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainterpath.h \
		../QT/5.12.12/gcc_64/include/QtGui/qimage.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixelformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixmap.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfont.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontmetrics.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontinfo.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qsizepolicy.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcursor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qkeysequence.h \
		../QT/5.12.12/gcc_64/include/QtGui/qevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurlquery.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector2d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtouchdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintengine.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainter.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtextoption.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpen.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qglcolormap.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/QByteArray \
		../QT/5.12.12/gcc_64/include/QtGui/QImage \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLFramebufferObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector3d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector4d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix4x4.h \
		../QT/5.12.12/gcc_64/include/QtGui/qquaternion.h \
		../QT/5.12.12/gcc_64/include/QtGui/qgenericmatrix.h \
		experiment/forexperiment.h \
		../QT/5.12.12/gcc_64/include/QtCore/QElapsedTimer \
		../QT/5.12.12/gcc_64/include/QtCore/qelapsedtimer.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/QApplication \
		../QT/5.12.12/gcc_64/include/QtWidgets/qapplication.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreapplication.h \
		../QT/5.12.12/gcc_64/include/QtCore/qeventloop.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../QT/5.12.12/gcc_64/include/QtGui/qguiapplication.h \
		../QT/5.12.12/gcc_64/include/QtGui/qinputmethod.h \
		../QT/5.12.12/gcc_64/include/QtCore/QFile \
		../QT/5.12.12/gcc_64/include/QtCore/QTextStream \
		../QT/5.12.12/gcc_64/include/QtCore/QDebug \
		../QT/5.12.12/gcc_64/include/QtCore/QMap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DataHandler.o: db/DataHandler.cpp db/DataHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QVector \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtGui/QPolygonF \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		../QT/5.12.12/gcc_64/include/QtCore/QString \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/clip2tri/clip2tri.h \
		experiment/forexperiment.h \
		../QT/5.12.12/gcc_64/include/QtCore/QElapsedTimer \
		../QT/5.12.12/gcc_64/include/QtCore/qelapsedtimer.h \
		../QT/5.12.12/gcc_64/include/QtCore/QDebug \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/QFile \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/QFileInfo \
		../QT/5.12.12/gcc_64/include/QtCore/qfileinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/QTextStream
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataHandler.o db/DataHandler.cpp

clip2tri.o: triangulation/clip2tri/clip2tri.cpp triangulation/clip2tri/clip2tri.h \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clip2tri.o triangulation/clip2tri/clip2tri.cpp

clipper.o: triangulation/clipper/clipper.cpp triangulation/clipper/clipper.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipper.o triangulation/clipper/clipper.cpp

shapes.o: triangulation/poly2tri/common/shapes.cc triangulation/poly2tri/common/shapes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shapes.o triangulation/poly2tri/common/shapes.cc

advancing_front.o: triangulation/poly2tri/sweep/advancing_front.cc triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/common/shapes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o advancing_front.o triangulation/poly2tri/sweep/advancing_front.cc

cdt.o: triangulation/poly2tri/sweep/cdt.cc triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdt.o triangulation/poly2tri/sweep/cdt.cc

sweep.o: triangulation/poly2tri/sweep/sweep.cc triangulation/poly2tri/sweep/sweep.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/common/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sweep.o triangulation/poly2tri/sweep/sweep.cc

sweep_context.o: triangulation/poly2tri/sweep/sweep_context.cc triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/common/shapes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sweep_context.o triangulation/poly2tri/sweep/sweep_context.cc

GLData.o: join/GLData.cpp join/GLData.hpp \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qgl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qt_windows.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengles2ext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglext.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qwidget.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs_win.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintdevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpalette.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcolor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgb.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgba64.h \
		../QT/5.12.12/gcc_64/include/QtGui/qbrush.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qregion.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdatastream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qline.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtransform.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainterpath.h \
		../QT/5.12.12/gcc_64/include/QtGui/qimage.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixelformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfont.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontmetrics.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontinfo.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qsizepolicy.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcursor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qkeysequence.h \
		../QT/5.12.12/gcc_64/include/QtGui/qevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurlquery.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector2d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtouchdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintengine.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainter.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtextoption.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpen.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qglcolormap.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/QSurfaceFormat \
		../QT/5.12.12/gcc_64/include/QtGui/qsurfaceformat.h \
		../QT/5.12.12/gcc_64/include/QtCore/QByteArray \
		../QT/5.12.12/gcc_64/include/QtGui/QImage \
		../QT/5.12.12/gcc_64/include/QtCore/QSharedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLFramebufferObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector3d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector4d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix4x4.h \
		../QT/5.12.12/gcc_64/include/QtGui/qquaternion.h \
		../QT/5.12.12/gcc_64/include/QtGui/qgenericmatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLData.o join/GLData.cpp

GLFunction.o: join/GLFunction.cpp join/GLFunction.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QVector \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtCore/QPointF \
		../QT/5.12.12/gcc_64/include/QtCore/QSize \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		join/GLData.hpp \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qgl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qt_windows.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengles2ext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglext.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qwidget.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs_win.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintdevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpalette.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcolor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgb.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgba64.h \
		../QT/5.12.12/gcc_64/include/QtGui/qbrush.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qregion.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdatastream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qline.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtransform.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainterpath.h \
		../QT/5.12.12/gcc_64/include/QtGui/qimage.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixelformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfont.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontmetrics.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontinfo.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qsizepolicy.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcursor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qkeysequence.h \
		../QT/5.12.12/gcc_64/include/QtGui/qevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurlquery.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector2d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtouchdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintengine.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainter.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtextoption.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpen.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qglcolormap.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/QSurfaceFormat \
		../QT/5.12.12/gcc_64/include/QtGui/qsurfaceformat.h \
		../QT/5.12.12/gcc_64/include/QtCore/QByteArray \
		../QT/5.12.12/gcc_64/include/QtGui/QImage \
		../QT/5.12.12/gcc_64/include/QtCore/QSharedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLFramebufferObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector3d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector4d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix4x4.h \
		../QT/5.12.12/gcc_64/include/QtGui/qquaternion.h \
		../QT/5.12.12/gcc_64/include/QtGui/qgenericmatrix.h \
		join/GLHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLContext \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglcontext.h \
		../QT/5.12.12/gcc_64/include/QtCore/QObject \
		../QT/5.12.12/gcc_64/include/QtCore/QScopedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOffscreenSurface \
		../QT/5.12.12/gcc_64/include/QtGui/qoffscreensurface.h \
		../QT/5.12.12/gcc_64/include/QtGui/qsurface.h \
		db/DataHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QPolygonF \
		../QT/5.12.12/gcc_64/include/QtCore/QString \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/clip2tri/clip2tri.h \
		../QT/5.12.12/gcc_64/include/QtCore/QElapsedTimer \
		../QT/5.12.12/gcc_64/include/QtCore/qelapsedtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLFunction.o join/GLFunction.cpp

GLHandler.o: join/GLHandler.cpp join/GLHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLContext \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglcontext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/QObject \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/QScopedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/QSurfaceFormat \
		../QT/5.12.12/gcc_64/include/QtGui/qsurfaceformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qt_windows.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengles2ext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOffscreenSurface \
		../QT/5.12.12/gcc_64/include/QtGui/qoffscreensurface.h \
		../QT/5.12.12/gcc_64/include/QtGui/qsurface.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		../QT/5.12.12/gcc_64/include/QtCore/QSharedPointer \
		../QT/5.12.12/gcc_64/include/QtCore/QVector \
		join/GLFunction.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QPointF \
		../QT/5.12.12/gcc_64/include/QtCore/QSize \
		join/GLData.hpp \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qgl.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qwidget.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs_win.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintdevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpalette.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcolor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgb.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgba64.h \
		../QT/5.12.12/gcc_64/include/QtGui/qbrush.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qregion.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdatastream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qline.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtransform.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainterpath.h \
		../QT/5.12.12/gcc_64/include/QtGui/qimage.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixelformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixmap.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfont.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontmetrics.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontinfo.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qsizepolicy.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcursor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qkeysequence.h \
		../QT/5.12.12/gcc_64/include/QtGui/qevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurlquery.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector2d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtouchdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintengine.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainter.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtextoption.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpen.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qglcolormap.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/QByteArray \
		../QT/5.12.12/gcc_64/include/QtGui/QImage \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLFramebufferObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector3d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector4d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix4x4.h \
		../QT/5.12.12/gcc_64/include/QtGui/qquaternion.h \
		../QT/5.12.12/gcc_64/include/QtGui/qgenericmatrix.h \
		db/DataHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QPolygonF \
		../QT/5.12.12/gcc_64/include/QtCore/QString \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/clip2tri/clip2tri.h \
		../QT/5.12.12/gcc_64/include/QtCore/QDebug \
		join/RasterJoin.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLHandler.o join/GLHandler.cpp

RasterJoin.o: join/RasterJoin.cpp join/RasterJoin.hpp \
		join/GLFunction.hpp \
		../QT/5.12.12/gcc_64/include/QtCore/QVector \
		../QT/5.12.12/gcc_64/include/QtCore/qvector.h \
		../QT/5.12.12/gcc_64/include/QtCore/qalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobal.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../QT/5.12.12/gcc_64/include/QtCore/qconfig.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtcore-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsystemdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qprocessordetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcompilerdetection.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtypeinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsysinfo.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlogging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qflags.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbasicatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qgenericatomic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_cxx11.h \
		../QT/5.12.12/gcc_64/include/QtCore/qatomic_msvc.h \
		../QT/5.12.12/gcc_64/include/QtCore/qglobalstatic.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmutex.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnumeric.h \
		../QT/5.12.12/gcc_64/include/QtCore/qversiontagging.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiterator.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrefcount.h \
		../QT/5.12.12/gcc_64/include/QtCore/qarraydata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhashfunctions.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstring.h \
		../QT/5.12.12/gcc_64/include/QtCore/qchar.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qnamespace.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringliteral.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringalgorithms.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringview.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringbuilder.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpair.h \
		../QT/5.12.12/gcc_64/include/QtCore/qbytearraylist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringlist.h \
		../QT/5.12.12/gcc_64/include/QtCore/qregexp.h \
		../QT/5.12.12/gcc_64/include/QtCore/qstringmatcher.h \
		../QT/5.12.12/gcc_64/include/QtCore/qpoint.h \
		../QT/5.12.12/gcc_64/include/QtCore/QPointF \
		../QT/5.12.12/gcc_64/include/QtCore/QSize \
		../QT/5.12.12/gcc_64/include/QtCore/qsize.h \
		join/GLData.hpp \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qgl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtguiglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtgui-config.h \
		../QT/5.12.12/gcc_64/include/QtCore/qt_windows.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopengles2ext.h \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglext.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qwidget.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qwindowdefs_win.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcoreevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qscopedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmetatype.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvarlengtharray.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontainerfwd.h \
		../QT/5.12.12/gcc_64/include/QtCore/qobject_impl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmargins.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintdevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qrect.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpalette.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcolor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgb.h \
		../QT/5.12.12/gcc_64/include/QtGui/qrgba64.h \
		../QT/5.12.12/gcc_64/include/QtGui/qbrush.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpolygon.h \
		../QT/5.12.12/gcc_64/include/QtGui/qregion.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdatastream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qiodevice.h \
		../QT/5.12.12/gcc_64/include/QtCore/qline.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtransform.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainterpath.h \
		../QT/5.12.12/gcc_64/include/QtGui/qimage.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixelformat.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpixmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer.h \
		../QT/5.12.12/gcc_64/include/QtCore/qshareddata.h \
		../QT/5.12.12/gcc_64/include/QtCore/qhash.h \
		../QT/5.12.12/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfont.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontmetrics.h \
		../QT/5.12.12/gcc_64/include/QtGui/qfontinfo.h \
		../QT/5.12.12/gcc_64/include/QtWidgets/qsizepolicy.h \
		../QT/5.12.12/gcc_64/include/QtGui/qcursor.h \
		../QT/5.12.12/gcc_64/include/QtGui/qkeysequence.h \
		../QT/5.12.12/gcc_64/include/QtGui/qevent.h \
		../QT/5.12.12/gcc_64/include/QtCore/qvariant.h \
		../QT/5.12.12/gcc_64/include/QtCore/qmap.h \
		../QT/5.12.12/gcc_64/include/QtCore/qdebug.h \
		../QT/5.12.12/gcc_64/include/QtCore/qtextstream.h \
		../QT/5.12.12/gcc_64/include/QtCore/qlocale.h \
		../QT/5.12.12/gcc_64/include/QtCore/qset.h \
		../QT/5.12.12/gcc_64/include/QtCore/qcontiguouscache.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurl.h \
		../QT/5.12.12/gcc_64/include/QtCore/qurlquery.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfile.h \
		../QT/5.12.12/gcc_64/include/QtCore/qfiledevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector2d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtouchdevice.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpaintengine.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpainter.h \
		../QT/5.12.12/gcc_64/include/QtGui/qtextoption.h \
		../QT/5.12.12/gcc_64/include/QtGui/qpen.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qglcolormap.h \
		../QT/5.12.12/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		../QT/5.12.12/gcc_64/include/QtGui/QSurfaceFormat \
		../QT/5.12.12/gcc_64/include/QtGui/qsurfaceformat.h \
		../QT/5.12.12/gcc_64/include/QtCore/QByteArray \
		../QT/5.12.12/gcc_64/include/QtGui/QImage \
		../QT/5.12.12/gcc_64/include/QtCore/QSharedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLFramebufferObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector3d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qvector4d.h \
		../QT/5.12.12/gcc_64/include/QtGui/qmatrix4x4.h \
		../QT/5.12.12/gcc_64/include/QtGui/qquaternion.h \
		../QT/5.12.12/gcc_64/include/QtGui/qgenericmatrix.h \
		join/GLHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLContext \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglcontext.h \
		../QT/5.12.12/gcc_64/include/QtCore/QObject \
		../QT/5.12.12/gcc_64/include/QtCore/QScopedPointer \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOffscreenSurface \
		../QT/5.12.12/gcc_64/include/QtGui/qoffscreensurface.h \
		../QT/5.12.12/gcc_64/include/QtGui/qsurface.h \
		db/DataHandler.hpp \
		../QT/5.12.12/gcc_64/include/QtGui/QPolygonF \
		../QT/5.12.12/gcc_64/include/QtCore/QString \
		triangulation/clipper/clipper.hpp \
		triangulation/poly2tri/poly2tri.h \
		triangulation/poly2tri/common/shapes.h \
		triangulation/poly2tri/sweep/cdt.h \
		triangulation/poly2tri/sweep/advancing_front.h \
		triangulation/poly2tri/sweep/sweep_context.h \
		triangulation/poly2tri/sweep/sweep.h \
		triangulation/clip2tri/clip2tri.h \
		experiment/forexperiment.h \
		../QT/5.12.12/gcc_64/include/QtCore/QElapsedTimer \
		../QT/5.12.12/gcc_64/include/QtCore/qelapsedtimer.h \
		../QT/5.12.12/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../QT/5.12.12/gcc_64/include/QtGui/qopenglvertexarrayobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RasterJoin.o join/RasterJoin.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

